backend/src/main/java/us/stcorp/team3/hackathonproject/common/BaseTimeEntity.java, backend/src/main/java/us/stcorp/team3/hackathonproject/domain/Matzip.java, backend/src/main/java/us/stcorp/team3/hackathonproject/domain/MatzipReview.java
=> [refactor] 도메인 수정

frontend/src/components/EditorForm/EditorForm.jsx, frontend/src/components/EditorForm/index.js, frontend/src/components/Filter/Filter.jsx, frontend/src/components/PlaceHeader/PlaceHeader.jsx, frontend/src/components/RecommendedPlace/RecommendedPlace.jsx, frontend/src/components/ReviewInput/ReviewInput.jsx, frontend/src/components/common/BackButton/BackButton.jsx, frontend/src/components/common/BackButton/index.js, frontend/src/components/common/GradientButton/GradientButton.jsx, frontend/src/components/common/GradientButton/index.js, frontend/src/components/common/Header/Header.tsx, frontend/src/components/common/SelectBox/SelectBox.jsx, frontend/src/components/common/SelectBox/index.js, frontend/src/components/common/StarRating/StarRating.jsx, frontend/src/components/common/TextInput/TextInput.jsx, frontend/src/components/common/TextInput/index.js, frontend/src/pages/Editor.jsx, frontend/src/pages/Home.tsx, frontend/src/pages/Place.jsx, frontend/src/pages/RedirectToErrorPage.tsx, frontend/src/router/paths.ts, frontend/src/router/routes.ts, frontend/src/styles/theme.ts
=> [Feat/fe#19] Edit Page 마크업 

ml-server/utils/DBHelper.py
- DB 스키마 변경에 따른 SQL Query 변경
- `/utils/DBHelper.py`
=>  [PR] DB 스키마 변경에 따른 SQL Query 변경 (#34)

README.md
=> [PR] ML README

backend/build.gradle, backend/src/main/resources/application.yaml
Resolved Issue #57 
- 의존성 추가
- application.yaml 정의
=> [PR] BE OpenAPI 구축

backend/build.gradle, backend/src/main/java/us/stcorp/team3/hackathonproject/controller/MatzipController.java, backend/src/main/java/us/stcorp/team3/hackathonproject/dto/EntireMatzipResponse.java, backend/src/main/java/us/stcorp/team3/hackathonproject/dto/MatzipResponse.java, backend/src/main/java/us/stcorp/team3/hackathonproject/dto/ReviewResponse.java, backend/src/main/java/us/stcorp/team3/hackathonproject/repository/ReviewRepository.java, backend/src/main/java/us/stcorp/team3/hackathonproject/service/MatzipService.java, backend/src/main/resources/application.yaml, backend/src/test/java/us/stcorp/team3/hackathonproject/controller/MatzipControllerTest.java
- DTO 생성
- 비즈니스 로직 구현
- 컨트롤러 메서드 추가
- `Review`조회를 위한 레포지토리 생성
=> [Feat] 맛집 상제 조회

frontend/package.json, frontend/src/components/EditorForm/EditorForm.jsx, frontend/src/components/MyMenu/MyMenu.jsx, frontend/src/components/MyMenu/index.js, frontend/src/components/PlaceCard/PlaceCard.jsx, frontend/src/components/PlaceReviewCard/PlaceReviewCard.jsx, frontend/src/components/common/Header/Header.tsx, frontend/src/components/common/SelectModal/SelectModal.jsx, frontend/src/components/common/Spinner/Spinner.tsx, frontend/src/pages/Home.tsx, frontend/src/router/paths.ts, frontend/src/router/routes.ts, frontend/src/store/homeStore.js, frontend/src/util/API/index.js, frontend/src/util/API/instance.js, frontend/src/util/API/interceptor.js, frontend/yarn.lock
=> [Feat/fe#11,#55] Home UI(pagination, myMenu) 구현

backend/src/main/java/us/stcorp/team3/hackathonproject/controller/MatzipController.java, backend/src/main/java/us/stcorp/team3/hackathonproject/domain/MatzipReview.java, backend/src/main/java/us/stcorp/team3/hackathonproject/dto/MatzipReviewRequest.java, backend/src/main/java/us/stcorp/team3/hackathonproject/service/MatzipReviewService.java, backend/src/test/java/us/stcorp/team3/hackathonproject/controller/MatzipControllerTest.java
- DTO 생성
- 비즈니스 로직추가
- 컨트롤러 api 추가
=> [Feat] 맛집 리뷰 등록

ml-server/utils/DBHelper.py
Resolved Issue #64
- naver_comments -> naver_comment
=> [PR] ML SQL 변경

backend/src/main/java/us/stcorp/team3/hackathonproject/controller/MatzipController.java, backend/src/main/java/us/stcorp/team3/hackathonproject/service/MatzipReviewService.java
=> [Feat] 맛집 리뷰 삭제 기능 구현

backend/src/main/java/us/stcorp/team3/hackathonproject/controller/MatzipController.java, backend/src/main/java/us/stcorp/team3/hackathonproject/domain/Matzip.java, backend/src/main/java/us/stcorp/team3/hackathonproject/service/MatzipService.java
- `JPA Dirty Checking`을 사용한 맛집 수정 기능 추가
=> [Feat] 맛집 수정 기능

backend/src/main/java/us/stcorp/team3/hackathonproject/domain/Matzip.java, backend/src/main/java/us/stcorp/team3/hackathonproject/service/MatzipService.java
- `JPA Dirty Checking`을 이용해 상세 조회를 할 때마다 조회수 증가
=> [Feat] 조회수 증가 기능

backend/build.gradle, backend/src/main/java/us/stcorp/team3/hackathonproject/controller/MatzipController.java, backend/src/main/java/us/stcorp/team3/hackathonproject/repository/MatzipRepository.java, backend/src/main/java/us/stcorp/team3/hackathonproject/repository/ReviewRepository.java, backend/src/main/java/us/stcorp/team3/hackathonproject/service/MatzipReviewService.java, backend/src/main/java/us/stcorp/team3/hackathonproject/service/MatzipService.java
- queryDsl 적용
- queryDsl가 제공하는 avg() 통해 평점을 가져온 후, matzip 평균 평점 column UPDATE 로직 추가 구현
- update 이렇게 하는게 좋은지 의견 마구마구 주세요~
=> [Refactor] 맛집 리뷰 삭제시 맛집 평점에 반영

backend/src/main/java/us/stcorp/team3/hackathonproject/service/MatzipReviewService.java
=> refactor: 맛집 리뷰 등록시 맛집 평점에 반영 (#67)

backend/src/main/java/us/stcorp/team3/hackathonproject/common/config/QuerydslConfig.java, backend/src/main/java/us/stcorp/team3/hackathonproject/controller/MatzipController.java, backend/src/main/java/us/stcorp/team3/hackathonproject/dto/MatzipResponse.java, backend/src/main/java/us/stcorp/team3/hackathonproject/repository/MatzipRepository.java, backend/src/main/java/us/stcorp/team3/hackathonproject/repository/MatzipRepositoryCustom.java, backend/src/main/java/us/stcorp/team3/hackathonproject/repository/MatzipRepositoryImpl.java, backend/src/main/java/us/stcorp/team3/hackathonproject/service/MatzipReviewService.java, backend/src/main/java/us/stcorp/team3/hackathonproject/service/MatzipService.java, backend/src/test/java/us/stcorp/team3/hackathonproject/controller/MatzipControllerTest.java
- `Pageable`을 프론트에서 사용할 수 있도록 변경
- Querydsl 사용
=> [Refactor] 응답 스펙 변경

backend/src/main/java/us/stcorp/team3/hackathonproject/repository/MatzipRepositoryImpl.java
=> ✨ refactor: 평점별 Sorting - #77

frontend/src/components/Filter/Filter.jsx, frontend/src/pages/Home.jsx, frontend/src/store/homeStore.js
#81 
- 일반 Pagination
- 필터 클릭시 Pagination
Pagination 아주 자아알 됩니다!
=> [Feat/fe#81] Pagination 적용

frontend/src/components/PlaceCard/PlaceCard.jsx
=> feat: 추천 맛집으로 이동 구현 (#83)

frontend/src/components/EditorForm/EditorForm.jsx, frontend/src/components/PlaceReviewCard/PlaceReviewCard.jsx, frontend/src/components/ReviewInput/ReviewInput.jsx, frontend/src/components/common/PlaceCarousel/PlaceCarousel.jsx, frontend/src/components/common/SelectBox/SelectBox.jsx, frontend/src/components/common/SelectModal/SelectModal.jsx, frontend/src/pages/Home.jsx, frontend/src/service/EditorService.js
#80 
맛집 추가, 삭제되지롱~~
- 페이지네이션 1 더해서 보여주는 문제 해결 
- 리뷰 작성 후 리렌더링 안되는 문제 임시 해결
끝이 보입니다 화이팅~~~
=> [Feat/fe#80] 맛집 추가, 삭제 기능 구현

frontend/src/components/ReviewInput/ReviewInput.jsx
=> fix: postReview 안되는 문제 해결

backend/src/main/java/us/stcorp/team3/hackathonproject/service/MatzipReviewService.java
=> refactor: 맛집 리뷰 삭제 문제 해결

frontend/src/components/PlaceReview/PlaceReview.jsx, frontend/src/pages/Place.jsx, frontend/src/service/EditorService.js, frontend/src/store/editorStore.js, frontend/src/store/homeStore.js, frontend/src/store/placeStore.js
=> [Feat/fe#52] 불필요한 코드 삭제
